name: bios8366
dependencies:
- python=3.5
- basemap
- bokeh
- cython
- dask
- ipython
- jupyter
- notebook
- ipyparallel
- ipywidgets
- jupyter_client
- jupyter_core
- line_profiler
- numexpr
- numba
- numpy>=1.11.0
- pandas>=0.18.1
- patsy
- pillow
- pip
- scikit-learn>=0.17.1
- scipy>=0.17.1
- seaborn>=0.7.0
- snakeviz
- sympy
- theano
- xlrd
- pip:
  - git+https://github.com/pymc-devs/pymc3.git#egg=pymc3
  - GPy